fix: TypeError
 File "/root/.local/lib/python3.10/site-packages/dirsearch/lib/core/options.py", line 50, in options                                                                                                               
    elif not len(opt.urls):                                                                               
TypeError: object of type 'NoneType' has no len()

The error was caused because of the usage of the len() for a none type object.
Removing the len() function fixes the problem!